# Site settings
title: The Iron Yard Indianapolis - Ruby on Rails - October 2015
email: chris.vannoy@theironyard.com
description: > # this means to ignore newlines until "baseurl:"
  The Iron Yard Indianapolis Ruby on Rails Engineering course kicks off
  in the fall of 2015. This site contains (ideally) all the information you need
  before class starts.
baseurl: "/course_notes" # the subpath of your site, e.g. /blog/
url: "http://the-iron-yard-indy-ror-oct-2015.github.io" # the base hostname & protocol for your site
twitter_username: chris_vannoy
github_username:  dummied

# Build settings
markdown: kramdown
